### ISSUE TITLE
_data directory not found 

### ISSUE THREAD

**Issue by rgghodke77** [SajidAnTechie/ShopingPoint#1]
Hello _data directory is not in the code . Not able to upload mongodb database

**Comment by SajidAnTechie** [comment]
Bro u can create data through api endpoint using post man....
I have some credentials inside data directory which can't be public

**Comment by SajidAnTechie** [comment]
I will be posting data directory later after removing some credentials..stay tuned

**Comment by rgghodke77** [comment]
OK thanks

**Comment by SajidAnTechie** [comment]
data folder added
